import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/toaster";
import ProvidersRedux from "@/redux/Providers";
import { getServerSession } from "next-auth";
import auth from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  previewListener, // Add any extra attributes you want to pass
}: Readonly<{
  children: React.ReactNode;
  previewListener?: any; // Define the type according to your requirements
}>) {
  const session = await getServerSession(auth);
  return (
    <>
      <html lang="en">
        <head />
        <body className={inter.className} suppressHydrationWarning={true}>
          <Providers session={session}>
            <ProvidersRedux>
              {children}
              <Toaster />
            </ProvidersRedux>
          </Providers>
        </body>
      </html>
    </>
  );
}
